[package]
name = "eco_print"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bluest = { version = "0.6.6", optional = true }
rusb = { version = "0.9.3", optional = true }
futures-lite = { version = "1.13.0", default-features = false, optional = true }


[features]
default = ["escpos"]
ender3v2 = []
escpos = ["rusb", "bluest", "futures-lite"]

[dev-dependencies]
tokio = { version = "1.34.0", features = ["full"] }
