[package]
name = "    "
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bluest = "0.6.6"
futures-lite = { version = "1.13.0", default-features = false }
rusb = "0.9.3"
tokio = { version = "1.34.0", features = ["full"] }

[features]
default = ["escpos"]
ender3v2 = []
escpos = []
